### PR TITLE
enable ASAN for all builds

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by a-denoyelle** [comment]
It may be a good idea for the normal testcases. However, I'm wondering if there is any impact on performance for the measurement tests ?

**Comment by chipitsine** [comment]
no visible impact. even some other qns images are built using asan enabled by default

**Comment by chipitsine** [comment]
let me check perf testcases. brb soon

**Comment by chipitsine** [comment]
I've compared time taken for goodput,crosstraffic tests with and without ASAN, no difference.

I suggest to merge.

**Comment by a-denoyelle** [comment]
@chipitsine I have tried to use interop runner locally with newly ASAN built, but the test fails with a log full of lines `AddressSanitizer:DEADLYSIGNAL`. Did you know by any chance what could be the issue ?

**Comment by chipitsine** [comment]
as a wild guess, can it be some kernel feature ?

do you have ubuntu 24 as docker host to try ?
I recall running on Fedora 40, 41 - no issues.

**Comment by chipitsine** [comment]
something like that ? 

https://github.com/actions/runner-images/issues/9491

**Comment by a-denoyelle** [comment]
I'm running on Archlinux, kernel 6.11.5. Yes the issue sounds similar.

**Comment by chipitsine** [comment]
I've mentioned ubuntu 24, because we use them in GitHub Actions. But generally it won't work, because those image are tuned on sysctl side

**Pull request merged**
